

export default {
  CLICK: 'click',
  SCROLL: 'scroll',
  MOUSE_WHEEL: 'mousewheel',
  KEY_DOWN: 'keydown',
  RESIZE: 'resize',
  FOCUS: 'focus',
  BLUR: 'blur',
  ERROR: 'error',
  CHANGE: 'change',
  ANIMATION_END: 'animationend',
  TRANSITION_END: 'transitionend',
  WEBKIT_TRANSITION_END: 'webkitTransitionEnd',
  BEFORE_UNLOAD: 'beforeunload',
  MOUSE_DOWN: 'mousedown',
  MOUSE_UP: 'mouseup',
  MOUSE_MOVE: 'mousemove',
  TOUCH_START: 'touchstart',
  TOUCH_MOVE: 'touchmove',
  TOUCH_END: 'touchend',
  TOUCH_CANCEL: 'touchcancel',
  READER_GESTURE: 'readergesture',
};
