const STATUS_BAR_HEIGHT = 25;
const NAV_BAR_HEIGHT = 55;

const PAGE_MAX_WIDTH = 700;
const MIN_PADDING_BOTTOM = 50;
const MAX_PADDING_LEVEL = 6;
const DEFAULT_PADDING_VERTICAL = 35;
const EXTENDED_TOUCH_WIDTH = 100;
const CONTENT_FOOTER_HEIGHT = 60;
const PAGE_VIEWER_SELECTOR = '#viewer_contents .pages';
const SCROLL_VIEWER_SELECTOR = '#viewer_contents .pages';
const CHAPTER_INDICATOR_ID_PREFIX = 'ridi_link_c';
const CHAPTER_ID_PREFIX = 'ridi_c';

const mainMenuStyleConstants = {
  HEIGHT: 56,
  ITEM_WIDTH_ON_TABLET: 113,
};

const categoryStyleConstants = {
  TAB_HEADER_HEIGHT: 51,
  SUB_HEADER_HEIGHT: 50,
};

export {
  STATUS_BAR_HEIGHT,
  NAV_BAR_HEIGHT,
  PAGE_MAX_WIDTH,
  MIN_PADDING_BOTTOM,
  MAX_PADDING_LEVEL,
  DEFAULT_PADDING_VERTICAL,
  EXTENDED_TOUCH_WIDTH,
  PAGE_VIEWER_SELECTOR,
  SCROLL_VIEWER_SELECTOR,
  CONTENT_FOOTER_HEIGHT,
  CHAPTER_INDICATOR_ID_PREFIX,
  CHAPTER_ID_PREFIX,
  mainMenuStyleConstants,
  categoryStyleConstants,
};
