const DEFAULT_MAX_WIDTH = 700;
const DEFAULT_VERTICAL_MARGIN = 35;
const DEFAULT_HORIZONTAL_MARGIN = 30;
const DEFAULT_CONTENT_FOOTER_HEIGHT = 60;
const CHAPTER_INDICATOR_ID_PREFIX = 'ridi_link_c';
const CHAPTER_ID_PREFIX = 'ridi_c';
const DEFAULT_FONT = 'os_specific';

const SELECTION_LAYER_EXPANDED_WIDTH = 10;

export {
  DEFAULT_MAX_WIDTH,
  DEFAULT_VERTICAL_MARGIN,
  DEFAULT_HORIZONTAL_MARGIN,
  DEFAULT_CONTENT_FOOTER_HEIGHT,
  CHAPTER_INDICATOR_ID_PREFIX,
  CHAPTER_ID_PREFIX,
  DEFAULT_FONT,
  SELECTION_LAYER_EXPANDED_WIDTH,
};
