const STATUS_BAR_HEIGHT = 25;
const NAV_BAR_HEIGHT = 55;

const DEFAULT_MAX_WIDTH = 700;
const MAX_PADDING_LEVEL = 7;
const DEFAULT_VERTICAL_MARGIN = 35;
const DEFAULT_HORIZONTAL_MARGIN = 30;
const DEFAULT_EXTENDED_SIDE_TOUCH_WIDTH = 100;
const DEFAULT_CONTENT_FOOTER_HEIGHT = 60;
const READER_SELECTOR = '#reader_contents';
const CHAPTER_INDICATOR_ID_PREFIX = 'ridi_link_c';
const CHAPTER_ID_PREFIX = 'ridi_c';

export {
  STATUS_BAR_HEIGHT,
  NAV_BAR_HEIGHT,
  DEFAULT_MAX_WIDTH,
  MAX_PADDING_LEVEL,
  DEFAULT_VERTICAL_MARGIN,
  DEFAULT_HORIZONTAL_MARGIN,
  DEFAULT_EXTENDED_SIDE_TOUCH_WIDTH,
  READER_SELECTOR,
  DEFAULT_CONTENT_FOOTER_HEIGHT,
  CHAPTER_INDICATOR_ID_PREFIX,
  CHAPTER_ID_PREFIX,
};
