export const CALCULATION_INVALIDATE = Symbol('CALCULATION_INVALIDATE');
export const CALCULATION_SET = Symbol('CALCULATION_SET');

export const WITH_CALCULATION_TARGETS = Symbol('WITH_CALCULATION_TARGETS');
