export const CALCULATION_INVALIDATED = Symbol('CALCULATION_INVALIDATED');
export const CALCULATION_UPDATED = Symbol('CALCULATION_UPDATED');
export const READY_TO_READ = Symbol('READY_TO_READ');
export const CALCULATION_COMPLETED = Symbol('CALUCLATION_COMPLETED');

export const WITH_CALCULATION_TARGETS = Symbol('WITH_CALCULATION_TARGETS');


export const CALCULATION_TOTAL_UPDATED = Symbol('CALCULATION_TOTAL_UPDATED');


export const CALCULATE_CONTENT = Symbol('CALCULATE_CONTENT');
